date: "`r paste0(format(Sys.time(), '%B %d, %Y'))`"
page-navigation: true
site-url: "https://github.com/afsc-gap-products/gap_bs_data_report" 
repo-url: "https://github.com/afsc-gap-products/gap_bs_data_report"
repo-actions: [edit, source, issue]
favicon: img/favicon.png
downloads: [pdf, docx]
search: true
output-dir: ../docs

page-footer:
  right: "[U.S. Department of Commerce](https://www.commerce.gov/) | [National Oceanographic and Atmospheric Administration](https://www.noaa.gov) | [NOAA Fisheries](https://www.fisheries.noaa.gov/)" 
  left: "&copy; CC-1.0"
  
sidebar:
  background: "#D9E3E4"
  logo: "https://avatars.githubusercontent.com/u/91760178?s=96&amp;v=4"
  favicon: img/favicon.ico
  pinned: true
  align: center
  tools: 
    - icon: globe
      href: https://github.com/afsc-gap-products
      text: "AFSC GAP Survey Data Products"
  style: "docked"
  search: true
  collapse-level: 1
author:
  - name: Emily Markowitz
    orcid: 0000-0001-5757-4230
    email: emily.markowitz@noaa.gov 
    note: emilymarkowitz-noaa
    affiliations:
      - name: NOAA Fisheres Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team
  - name: Liz Dawson
    email: liz.dawson@noaa.gov    
    note: liz-dawson-NOAA
    affiliations:
      - name: NOAA Fisheries Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team
  - name: Chris Anderson
    email: christopher.anderson@noaa.gov   
    note: ChrisAnderson-NOAA
    affiliations:
      - name: NOAA Fisheries Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team
  - name: Sean Rohan
    email: sean.rohan@noaa.gov 
    note: sean-rohan-NOAA
    affiliations:
      - name: NOAA Fisheres Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team
  - name: Nicole Charriere
    email: nicole.charriere@noaa.gov    
    note: NicoleCharriere-NOAA
    affiliations:
      - name: NOAA Fisheries Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team
  - name: Duane Stevenson
    email: duane.stevenson@noaa.gov   
    note: Duane-Stevenson-NOAA
    affiliations:
      - name: NOAA Fisheries Alaska Fisheries Science Center
        department: Groundfish Assessment Program, Bering Sea Survey Team  

execute:
  echo: false
  eval: true
  error: false
  message: false
  comment: false
  warning: false
  code-overflow: wrap
  freeze: auto

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
    latex_engine: xelatex
    pandoc_args: "--latex-engine-opt=--enable-write18"
  docx:
    toc: true
    toc-depth: 2
    reference-doc: styles_reference.docx  # template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3
    number-sections: false
    include-before-body: translate.html   
    
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
link-citations: true

crossref:
  fig-title: "**Figure**"
plots:
  caption:
    style: Image Caption
    pre: 'Fig. '
    sep: '-- '
tables:
  caption:
    style: Table Caption
    pre: 'Table '
    sep: '.-- ' 
    
keywords:
  - Bering Sea
  - Alaska
  - fisheries
  - NOAA
  - groundfish

# filters:
#   # - assets/include-files.lua
#   - quarto
# 
# metadata-files:
#   - _frontmatter.yml
#   - quarto